// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7HX2qT5b5Cey3dqZiRdKd5GAvd3oCin8',
    appId: '1:209192778130:web:362f6030b9ee28722a694b',
    messagingSenderId: '209192778130',
    projectId: 'txeye-4ef13',
    authDomain: 'txeye-4ef13.firebaseapp.com',
    storageBucket: 'txeye-4ef13.firebasestorage.app',
    measurementId: 'G-91S6V7S6C3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAseorMQ_Xyk--8rqvjNl4Dp3FQxVv_-6U',
    appId: '1:209192778130:android:bde7ce41a447db8b2a694b',
    messagingSenderId: '209192778130',
    projectId: 'txeye-4ef13',
    storageBucket: 'txeye-4ef13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNvS1XUtNWBJcGcjPaoJ81Kx8kxC3i8W8',
    appId: '1:209192778130:ios:ce985519b471377d2a694b',
    messagingSenderId: '209192778130',
    projectId: 'txeye-4ef13',
    storageBucket: 'txeye-4ef13.firebasestorage.app',
    iosBundleId: 'com.etgkqo.txeye',
  );
}
